CREATE TABLE IF NOT EXISTS public.modules (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price_monthly INTEGER NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'SEK',
  stripe_price_id TEXT,
  vertical TEXT,
  is_free BOOLEAN DEFAULT true,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.user_modules (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  project_id UUID NOT NULL,
  module_id TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  activated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, project_id, module_id)
);

INSERT INTO public.modules (id, name, description, price_monthly, vertical, is_free) VALUES
('booking', 'Bokningssystem', 'Online-bokning för kunder', 199, 'hair_salon', true),
('loyalty', 'Lojalitetsprogram', 'Poäng och belöningar', 149, 'hair_salon', true),
('staff', 'Personalpresentation', 'Visa personal med specialiteter', 0, 'hair_salon', true),
('giftcard', 'Presentkort', 'Sälj presentkort online', 149, 'hair_salon', true),
('reservations', 'Bordsbokning', 'Hantera bordsreservationer', 199, 'restaurant', true),
('menu', 'Digital meny', 'QR-kod-meny med allergeninfo', 149, 'restaurant', true),
('takeaway', 'Take away-beställning', 'Online-beställning för avhämtning', 249, 'restaurant', true),
('reviews', 'Recensioner', 'Samla och visa kundrecensioner', 99, 'restaurant', true),
('clinic_booking', 'Patientbokning', 'Bokningssystem för klinik', 199, 'clinic', true),
('gdpr', 'GDPR-formulär', 'Samtycke och dataskydd', 99, 'clinic', true),
('journal', 'Journalsystem', 'Digital patientjournal', 299, 'clinic', true),
('telemedicine', 'Videokonsultation', 'Online-möten med patienter', 249, 'clinic', true),
('product_catalog', 'Produktkatalog', 'Hantera produkter och varianter', 0, 'e_commerce', true),
('checkout', 'Checkout', 'Säker betalning med Stripe', 0, 'e_commerce', true),
('inventory', 'Lagerhantering', 'Spåra lagerstatus i realtid', 199, 'e_commerce', true),
('discount', 'Rabattkoder', 'Skapa och hantera kampanjer', 99, 'e_commerce', true),
('wishlist', 'Önskelista', 'Låt kunder spara favoriter', 99, 'e_commerce', true),
('order_management', 'Orderhantering', 'Ta emot och hantera ordrar', 249, 'food_delivery', true),
('realtime_tracking', 'Realtidsspårning', 'GPS-spårning av leveranser', 299, 'food_delivery', true),
('restaurant_panel', 'Restaurangpanel', 'Dashboard för restauranger', 199, 'food_delivery', true),
('delivery_zones', 'Leveranszoner', 'Definiera leveransområden', 149, 'food_delivery', true),
('property_listings', 'Fastighetslistning', 'Visa objekt med bilder och priser', 199, 'real_estate', true),
('mortgage_calc', 'Bolånekalkylator', 'Beräkna månadskostnad', 0, 'real_estate', true),
('virtual_tour', 'Virtuell visning', '3D-rundtur i fastigheter', 299, 'real_estate', true),
('contact_broker', 'Kontakta mäklare', 'Direktkontakt med mäklare', 0, 'real_estate', true),
('case_intake', 'Ärendeformulär', 'Ta emot nya ärenden online', 199, 'law_firm', true),
('consultation_booking', 'Konsultationsbokning', 'Boka inledande samtal', 149, 'law_firm', true),
('document_signing', 'Dokumentsignering', 'Digital signering av avtal', 249, 'law_firm', true),
('class_booking', 'Klassbokning', 'Boka gymklasser online', 199, 'gym', true),
('membership', 'Medlemshantering', 'Hantera gymmedlemmar', 249, 'gym', true),
('pt_booking', 'PT-bokning', 'Boka personlig tränare', 149, 'gym', true),
('workout_plans', 'Träningsprogram', 'Anpassade träningsplaner', 149, 'gym', true),
('course_catalog', 'Kurskatalog', 'Lista och sälj kurser', 199, 'education', true),
('student_portal', 'Studentportal', 'Portal för studenter', 199, 'education', true),
('quiz', 'Quiz & Tester', 'Interaktiva tester', 149, 'education', true),
('certificates', 'Certifikat', 'Utfärda kursintyg automatiskt', 149, 'education', true),
('service_booking', 'Servicebeställning', 'Boka bilservice online', 199, 'auto_repair', true),
('vehicle_history', 'Fordonshistorik', 'Visa servicehistorik', 149, 'auto_repair', true),
('parts_order', 'Reservdelsbeställning', 'Beställ reservdelar', 199, 'auto_repair', true),
('client_portal', 'Kundportal', 'Portal för klientdokument', 199, 'accounting', true),
('invoice_generator', 'Fakturahantering', 'Skapa och skicka fakturor', 249, 'accounting', true),
('tax_calculator', 'Skattekalkylator', 'Beräkna skatt och moms', 149, 'accounting', true),
('room_booking', 'Rumsbokning', 'Online-bokning av rum', 249, 'hotel', true),
('checkin_online', 'Online check-in', 'Digital incheckning', 199, 'hotel', true),
('concierge', 'Concierge-tjänster', 'Beställ tjänster från rummet', 149, 'hotel', true),
('event_registration', 'Eventregistrering', 'Anmälan till evenemang', 149, 'event_planning', true),
('ticket_sales', 'Biljettförsäljning', 'Sälj biljetter online', 199, 'event_planning', true),
('seating_plan', 'Sittningsplan', 'Hantera bordsplacering', 149, 'event_planning', true),
('portfolio_gallery', 'Portföljgalleri', 'Visa foton professionellt', 0, 'photography', true),
('shoot_booking', 'Fotobookning', 'Boka fotografering', 149, 'photography', true),
('photo_delivery', 'Fotoleverans', 'Leverera foton digitalt', 149, 'photography', true),
('leads', 'Lead Generator', 'Fånga och kvalificera leads med AI', 249, NULL, true),
('chat_support', 'AI Chatt-support', 'Automatisk kundtjänst', 199, NULL, true),
('analytics', 'Besöksanalys', 'Spåra besökare och konverteringar', 149, NULL, true),
('newsletter', 'Nyhetsbrev', 'Samla e-postprenumeranter', 99, NULL, true),
('social_feed', 'Social media-flöde', 'Visa Instagram/Facebook-flöde', 99, NULL, true),
('cookie_consent', 'Cookie-samtycke', 'GDPR-kompatibelt cookie-banner', 0, NULL, true),
('multilang', 'Flerspråkig', 'Översätt hemsidan automatiskt', 199, NULL, true),
('seo_tools', 'SEO-verktyg', 'Optimera för sökmotorer', 149, NULL, true)
ON CONFLICT (id) DO NOTHING;
